# Use an official Node.js runtime as a parent image
FROM node:20.12.2

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY package*.json .

# Bundle your app source
COPY . .

RUN npm install

# Expose the port Next.js runs on
EXPOSE 3000

# Define the command to run your app using CMD
CMD ["npm", "run", "dev"]
