# Use an official Node.js runtime as a parent image
FROM node:20.12.2

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY package*.json .

# Bundle your app source
COPY . .

RUN npm install

# Build the Next.js application
RUN npm run build

# Expose the port Next.js runs on
ENV PORT=4000
EXPOSE 4000

# Define the command to run your app using CMD
CMD ["npm", "run", "start"]
