name: Next JS continuous integration

on:
  push:
    branches:
      - main  # Replace with your main branch name
      - master  # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system environment

    steps:
    - uses: actions/checkout@v2  # Checks out your repository's code

    - name: Set up Node.js  # Example for Node.js project (adjust as per your project)
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'  # Specify Node.js version

    - name: Install dependencies
      run: npm install  # Replace with your package manager command if using another language

    # Add more steps as needed, such as build, lint, deploy, etc.
