name: Next JS continuous integration

on:
  push:
    branches:
      - main  # Replace with your main branch name
      - master  # Add more branches as needed
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system environment

    steps:
    - uses: actions/checkout@v2  # Checks out your repository's code

    - name: Set up Node.js  # Example for Node.js project (adjust as per your project)
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'  # Specify Node.js version

    - name: Install dependencies
      run: npm install  # Replace with your package manager command if using another language

    # Add more steps as needed, such as build, lint, deploy, etc.
    - name: Build Docker Image
      run: docker build -t nextjs14cicd-docker:1.0 .

  # deploy:
  #   name: Deploy to Heroku
  #   needs: build-and-test
  #   if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '20.9.0'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build Docker Image
  #       run: docker-compose up --build -d

  #     #   - name: Pull and Deploy Docker Image to Heroku
  #     #     run: |
  #     #       heroku container:login
  #     #       heroku container:pull web next14-docker-cicd:1.0
  #     #       heroku container:release web -a next14-docker-cicd

  #     - name: Log in to the Heroku Container Registry
  #       run: heroku container:login
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  #     - name: Tag and Push Docker Image to Heroku
  #       run: |
  #         docker tag nextjs14cicd-docker:1.0 registry.heroku.com/nextjs14cicd-docker/web
  #         docker push registry.heroku.com/nextjs14cicd-docker/web
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  #     - name: Release the Image to Heroku
  #       run: heroku container:release web -a nextjs14cicd-docker
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}